# This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
      - uses: actions/checkout@v2

      - name: Run Lint
        run : dart analyze .

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/report/lint-results-debug.html


